version: '3.4'

services:
  traefikeditor:
    image: aesgarth/traefikeditor:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /path/to/traefik/data/configs/dynamic.yml:/data/dynamic.yml  # Mount your YAML file
